version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    container_name: tasks_postgres
    env_file:
      - .env.db
    ports:
      - '5434:5432'
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - tasks-network

volumes:
  postgres_vol:

networks:
  tasks-network: